engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 20
ratings:
  paths:
  - "**.js"
exclude_paths:
- "server/dist/"
- "node_modules/"
- "**/node_modules/"
- "**/api-docs/"