import keyMirror from 'keymirror-js';

const actions = [
  'ADD_FLASH_MESSAGE',
  'DELETE_FLASH_MESSAGE',
  'SET_CURRENT_USER',
  'SET_BOOKS',
  'BOOK_ADDED',
  'SET_IS_LOADING',
  'SET_IMAGE_DATA',
  'DELETE_IMAGE_DATA',
  'BOOK_FETCHED',
  'BOOK_UPDATED',
  'BOOK_DELETED',
  'BOOK_BORROWED',
  'GET_BORROWED_BOOKS',
  'BOOK_RETURNED',
  'CATEGORY_ADDED',
  'CATEGORY_FETCHED',
  'CATEGORY_EDITED',
  'CATEGORY_DELETED',
  'BOOKS_SEARCHED',
  'STOCK_MANAGER_FETCHED',
  'STOCK_ADDED',
  'STOCK_DELETED',
  'GET_BOOKS_HISTORIES',
  'GET_USERS',
  'USER_UPDATED'
];

export default keyMirror(actions);

