export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';

export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_BOOKS = 'SET_BOOKS';

export const ADD_BOOK = 'ADD_BOOK';

export const SET_IS_LOADING = 'SET_IS_LOADING';

export const SET_IMAGE_DATA = 'SET_IMAGE_DATA';

export const DELETE_IMAGE_DATA = 'DELETE_IMAGE_DATA';

export const BOOK_FETCHED = 'BOOK_FETCHED';

export const BOOK_UPDATED = 'BOOK_UPDATED';

export const BOOK_DELETED = 'BOOK_DELETED';

export const BOOK_BORROWED = 'BOOK_BORROWED';

export const BORROWED_BOOK = 'BORROWED_BOOK';

export const BOOK_RETURNED = 'BOOK_RETURNED';

export const CATEGORY_ADDED = 'CATEGORY_ADDED';

export const CATEGORY_FETCHED = 'CATEGORY_FETCHED';

export const CATEGORY_EDITED = 'CATEGORY_EDITED';

export const CATEGORY_DELETED = 'CATEGORY_DELETED';

export const BOOKS_SEARCHED = 'BOOKS_SEARCHED';

export const STOCK_MANAGER_FETCHED = 'STOCK_MANAGER_FETCHED';

export const STOCK_ADDED = 'STOCK_ADDED';

export const STOCK_DELETED = 'STOCK_DELETED';


